app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');

Route::pattern('id', '[0-9]+');
Route::get('news/{id}/item', 'NewsController@item');
Route::get('video/{id}/item', 'VideoController@item');
Route::get('photo/{id}/item', 'PhotoController@item');

Route::get('auth/login', 'Auth\AuthController@showLoginForm');
Route::post('auth/login', 'Auth\AuthController@login');
Route::get('auth/register', 'Auth\AuthController@showRegistrationForm');
Route::post('auth/register', 'Auth\AuthController@register');
Route::get('auth/logout', 'Auth\AuthController@logout');


if (Request::is('admin/*'))
{
    require __DIR__.'/admin_routes.php';
}

app/Role.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model {
    protected $fillable = [];
}

app/Http/Controllers/Admin/RoleController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AdminController;
use App\Role;
use App\Permission;
use App\PermissionRole;
use App\Http\Requests\Admin\RoleRequest;
use App\Http\Requests\Admin\DeleteRequest;
use Datatables;

class RoleController extends AdminController {
    /*
    * Display a listing of the resource.
    *
    * @return Response
    */
    public function index()
    {
        // Show the page
        return view('admin.roles.index');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function getCreate() {
        // Get all the available permissions
        $permissionsAdmin = Permission::where('is_admin','=',1)->get();
        $permissionsUser = Permission::where('is_admin','=',0)->get();
        // Selected permissions
        $permisionsadd =array();

        // Show the page
        return view('admin.roles.create_edit', compact('permissionsAdmin', 'permissionsUser','permisionsadd'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function postCreate(RoleRequest $request) {

        $is_admin = 0;
        // Check if role is for admin user
        if(!empty($request->permission)){
	    	$permissionsAdmin = Permission::where('is_admin','=',1)->get();
		    foreach ($permissionsAdmin as $perm){
	            foreach($request->permission as $item){
	                if($item==$perm['id'] && $perm['is_admin']=='1')
	                {
	                    $is_admin = 1;
	                }
	            }
	        }
		}
        $role = new Role();
        $role -> is_admin = $is_admin;
        $role -> name = $request->name;
        $role -> save();
		if(is_array($request->permission)){
	        foreach ($request->permission as $item) {
	            $permission = new PermissionRole();
	            $permission->permission_id = $item;
	            $permission->role_id = $role->id;
	            $permission -> save();
	        }
		}
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $role
     * @return Response
     */
    public function getEdit($id) {
        $role = Role::find($id);
        $permissionsAdmin = Permission::where('is_admin','=',1)->get();
        $permissionsUser = Permission::where('is_admin','=',0)->get();
        $permisionsadd = PermissionRole::where('role_id','=',$id)->select('permission_id')->get();

        // Show the page
        return view('admin.roles.create_edit', compact('role', 'permissionsAdmin', 'permissionsUser','permisionsadd'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param $role
     * @return Response
     */
    public function postEdit(RoleRequest $request, $id) {
        $is_admin = 0;
		if(!empty($request->permission)){
	        $permissionsAdmin = Permission::where('is_admin','=',1)->get();
	        foreach ($permissionsAdmin as $perm){
	            foreach($request->permission as $item){
	                if($item==$perm['id'] && $perm['is_admin']=='1')
	                {
	                    $is_admin = 1;
	                }
	            }
	        }
		}
        $role = Role::find($id);
        $role -> is_admin = $is_admin;
        $role -> name = $request->name;
        $role -> save();

        PermissionRole::where('role_id','=',$id) -> delete();
		
		if(is_array($request->permission)){
	        foreach ($request->permission as $item) {	        	
	            $permission = new PermissionRole();
	            $permission->permission_id = $item;
	            $permission->role_id = $role->id;
	            $permission -> save();
	        }
		}
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $role
     * @return Response
     */

    public function getDelete($id)
    {
        $role = Role::find($id);
        // Show the page
        return view('admin.roles.delete', compact('role'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $post
     * @return Response
     */
    public function postDelete(DeleteRequest $request,$id)
    {
        $role = Role::find($id);
        $role->delete();
    }
    /**
     * Show a list of all the languages posts formatted for Datatables.
     *
     * @return Datatables JSON
     */
    public function data()
    {
        $roles = Role::select(array('roles.id','roles.name','roles.created_at'));

        return Datatables::of($roles)
            ->add_column('actions', '<a href="{{{ URL::to(\'admin/roles/\' . $id . \'/edit\' ) }}}" class="btn btn-success btn-sm iframe" ><span class="glyphicon glyphicon-pencil"></span>  {{ Lang::get("admin/modal.edit") }}</a>
                    <a href="{{{ URL::to(\'admin/roles/\' . $id . \'/delete\' ) }}}" class="btn btn-sm btn-danger iframe"><span class="glyphicon glyphicon-trash"></span> {{ Lang::get("admin/modal.delete") }}</a>
                ')
            ->remove_column('id')
            ->make();
    }

}

resources/views/admin/roles/create_edit.blade.php
@extends('admin.layouts.modal') @section('content')
<ul class="nav nav-tabs">
	<li class="active"><a href="#tab-general" data-toggle="tab">{{{
			Lang::get('admin/modal.general') }}}</a></li>
</ul>
<form class="form-horizontal" method="post" action="" autocomplete="off">
	<input type="hidden" name="_token" value="{{{ csrf_token() }}}" />
	<div class="tab-content">
		<div class="tab-pane active" id="tab-general">
			<div class="col-md-12">
				<div
					class="form-group {{{ $errors->has('name') ? 'has-error' : '' }}}">
					<label class="col-md-2 control-label" for="name">{!!
						Lang::get('admin/role.name') !!}</label>
					<div class="col-md-10">
						<input class="form-control" type="text" name="name" id="name"
							value="{{{ Input::old('name', isset($role) ? $role->name : null) }}}" />
						{!! $errors->first('name', '<span class="help-inline">:message</span>')
						!!}
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="form-group">
					<label class="col-md-2 control-label" for="name">{!!
						Lang::get('admin/role.choose_role') !!}</label>
					<div class="col-md-10">
						<select tabindex="3" name="permission[]" id="permission"
							multiple="" style="width: 350px;"
							data-placeholder="{!! Lang::get('admin/role.choose_role') !!}">
							<optgroup label="{!! Lang::get('admin/role.userrole') !!}">
								@foreach ($permissionsUser as $permission)
								<option value="{{{ $permission['id'] }}}"
									@foreach($permisionsadd
									as $item)
		            		@if($item['permission_id']==$permission[
									'id']) selected='selected'
									;
		            		@endif
		            	@endforeach>{{{ $permission['display_name'] }}}</option>
								@endforeach
							</optgroup>
							<optgroup label="{!! Lang::get('admin/role.adminrole') !!}">
								@foreach ($permissionsAdmin as $permission)
								<option value="{{{ $permission['id'] }}}"
									@foreach($permisionsadd
									as $item)
		            		@if($item['permission_id']==$permission[
									'id']) selected='selected'
									;
		            		@endif
		            	@endforeach>{!! $permission['display_name'] !!}</option>
								@endforeach
							</optgroup>
						</select>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-12">
			<button type="reset" class="btn btn-sm btn-warning close_popup">
				<span class="glyphicon glyphicon-ban-circle"></span> {{
				Lang::get("admin/modal.cancel") }}
			</button>
			<button type="reset" class="btn btn-sm btn-default">
				<span class="glyphicon glyphicon-remove-circle"></span> {{
				Lang::get("admin/modal.reset") }}
			</button>
			<button type="submit" class="btn btn-sm btn-success">
				<span class="glyphicon glyphicon-ok-circle"></span> 
				    @if (isset($role)) 
				        {{ Lang::get("admin/modal.edit") }} 
				    @else 
				        {{Lang::get("admin/modal.create") }} 
				    @endif
			</button>
		</div>
	</div>
</form>
@stop @section('scripts')
<script type="text/javascript">
	$(function() {
		$("#permission").select2()
	});
</script>
@stop

resources/views/admin/roles/delete.blade.php
@extends('admin.layouts.modal') @section('content')
<ul class="nav nav-tabs">
	<li class="active"><a href="#tab-general" data-toggle="tab">{{
			Lang::get("admin/modal.general") }}</a></li>
</ul>
<form id="deleteForm" class="form-horizontal" method="post"
	action="@if (isset($role)){{ URL::to('admin/roles/' . $role->id . '/delete') }}@endif"
	autocomplete="off">
	<input type="hidden" name="_token" value="{{{ csrf_token() }}}" /> <input
		type="hidden" name="id" value="{{ $role->id }}" />
	<div class="form-group">
		<div class="controls">
			{{ Lang::get("admin/modal.delete_message") }}<br>
			<element class="btn btn-warning btn-sm close_popup">
			<span class="glyphicon glyphicon-ban-circle"></span> {{
			Lang::get("admin/modal.cancel") }}</element>
			<button type="submit" class="btn btn-sm btn-danger">
				<span class="glyphicon glyphicon-trash"></span> {{
				Lang::get("admin/modal.delete") }}
			</button>
		</div>
	</div>
</form>
@stop

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.default') {{-- Web site Title --}}
@section('title') {{{ Lang::get("admin/role.roles") }}} :: @parent @stop

{{-- Content --}} @section('content')
<div class="page-header">
	<h3>
		{{{ Lang::get("admin/role.roles") }}}
		<div class="pull-right">
			<div class="pull-right">
				<a href="{{{ URL::to('admin/roles/create') }}}"
					class="btn btn-sm  btn-primary iframe"><span
					class="glyphicon glyphicon-plus-sign"></span> {{
					Lang::get("admin/modal.new") }}</a>
			</div>
		</div>
	</h3>
</div>

<table id="table" class="table table-striped table-hover">
	<thead>
		<tr>
			<th>{{{ Lang::get("admin/modal.title") }}}</th>
			<th>{{{ Lang::get("admin/admin.created_at") }}}</th>
			<th>{{{ Lang::get("admin/admin.action") }}}</th>
		</tr>
	</thead>
	<tbody></tbody>
</table>
@stop {{-- Scripts --}} @section('scripts')
<script type="text/javascript">
	var oTable;
	$(document).ready(function() {
		oTable = $('#table').dataTable({
			"sDom" : "<'row'<'col-md-6'l><'col-md-6'f>r>t<'row'<'col-md-6'i><'col-md-6'p>>",
			"sPaginationType" : "bootstrap",
			
			"bProcessing" : true,
			"bServerSide" : true,
			"sAjaxSource" : "{{ URL::to('admin/roles/data/') }}",
			"fnDrawCallback" : function(oSettings) {
				$(".iframe").colorbox({
					iframe : true,
					width : "80%",
					height : "80%",
					onClosed : function() {
						window.location.reload();
					}
				});
			}
		});
	}); 
</script>
@stop